# Generated by Django 4.2.6 on 2023-11-20 05:55

from django.db import migrations


def make_political_parties(apps, schema_editor):
    PoliticalParty = apps.get_model("core", "PoliticalParty")
    PoliticalParty.objects.create(name="Democratic Party")
    PoliticalParty.objects.create(name="Green Party")
    PoliticalParty.objects.create(name="Libertarian Party")
    PoliticalParty.objects.create(name="Republican Party")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(make_political_parties, migrations.RunPython.noop)
    ]
